[package]
name = "staticfs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "staticfs"
path = "src/main.rs"

[dependencies]
env_logger = "0.11"
log = "0.4"
ntex = { version = "2.0", features = ["tokio"] }
ntex-files = "2.0.0"
